[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
environment = { path = "../environment" }
errors = { path = "../errors" }
database = { path = "../database" }
repository = { path = "../repository" }
service = { path = "../service" }
state = { path = "../state" }
controller = { path = "../controller" }
model = { path = "../model" }


axum = {version = "0.7.5",features = ["multipart"] }
tower-http = { version = "0.5.0", features = ["trace","limit"] }
redis = { version = "0.27.4", features = ["tokio-comp"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
async-trait = "0.1.80"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
utoipa-swagger-ui = { version = "8", features = ["axum"] }
utoipa-redoc = { version = "5", features = ["axum"] }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-axum = "0.1.0"


