[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
serde = "1.0"
serde_derive = "1.0"
surrealdb = "2.1.4"
axum = {version = "0.7.5",features = ["multipart"] }
uuid = { version = "1.3.0", features = ["serde", "v4"] }
validator = { version = "0.20", features = ["derive"] }
serde_json = "1.0.138"


